//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "device_config")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub device_uuid: String,
    #[sea_orm(unique)]
    pub device_id: Option<String>,
    pub device_name: String,
    pub device_token: Option<String>,
    pub server_url: Option<String>,
    pub company_name: Option<String>,
    pub company_tax_code: Option<String>,
    pub company_address: Option<String>,
    pub station_name: Option<String>,
    pub shop_name: Option<String>,
    pub license_key: Option<String>,
    pub license_expiry: Option<String>,
    pub last_sync_at: Option<String>,
    pub is_registered: bool,
    pub created_at: String,
    pub updated_at: String,
    pub company_phone: Option<String>,
    pub company_email: Option<String>,
    pub company_website: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub receipt_footer: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub receipt_template58mm: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub receipt_template80mm: Option<String>,
    pub qr_code_url: Option<String>,
    pub logo_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub label_template: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cameras::Entity")]
    Cameras,
    #[sea_orm(has_many = "super::cards::Entity")]
    Cards,
    #[sea_orm(has_many = "super::clients::Entity")]
    Clients,
    #[sea_orm(has_many = "super::contract_cars::Entity")]
    ContractCars,
    #[sea_orm(has_many = "super::contract_products::Entity")]
    ContractProducts,
    #[sea_orm(has_many = "super::contracts::Entity")]
    Contracts,
    #[sea_orm(has_many = "super::discounts::Entity")]
    Discounts,
    #[sea_orm(has_many = "super::dispenser_ports::Entity")]
    DispenserPorts,
    #[sea_orm(has_many = "super::dispensers::Entity")]
    Dispensers,
    #[sea_orm(has_many = "super::groups::Entity")]
    Groups,
    #[sea_orm(has_many = "super::limits::Entity")]
    Limits,
    #[sea_orm(has_many = "super::marks::Entity")]
    Marks,
    #[sea_orm(has_many = "super::nozzles::Entity")]
    Nozzles,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::prices::Entity")]
    Prices,
    #[sea_orm(has_many = "super::products::Entity")]
    Products,
    #[sea_orm(has_many = "super::roles::Entity")]
    Roles,
    #[sea_orm(has_many = "super::shifts::Entity")]
    Shifts,
    #[sea_orm(has_many = "super::tanks::Entity")]
    Tanks,
    #[sea_orm(has_many = "super::taxes::Entity")]
    Taxes,
    #[sea_orm(has_many = "super::units::Entity")]
    Units,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::cameras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cameras.def()
    }
}

impl Related<super::cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cards.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::contract_cars::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContractCars.def()
    }
}

impl Related<super::contract_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContractProducts.def()
    }
}

impl Related<super::contracts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contracts.def()
    }
}

impl Related<super::discounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discounts.def()
    }
}

impl Related<super::dispenser_ports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DispenserPorts.def()
    }
}

impl Related<super::dispensers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dispensers.def()
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groups.def()
    }
}

impl Related<super::limits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Limits.def()
    }
}

impl Related<super::marks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Marks.def()
    }
}

impl Related<super::nozzles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nozzles.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::prices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prices.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::shifts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shifts.def()
    }
}

impl Related<super::tanks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tanks.def()
    }
}

impl Related<super::taxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Taxes.def()
    }
}

impl Related<super::units::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Units.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
