//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "discounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub discount_type: String,
    pub discount_bound_type: String,
    pub discount_unit_type: String,
    pub product_type: Option<String>,
    pub bound: Decimal,
    pub value: Decimal,
    pub order_type: String,
    pub device_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contract_products::Entity")]
    ContractProducts,
    #[sea_orm(
        belongs_to = "super::device_config::Entity",
        from = "Column::DeviceId",
        to = "super::device_config::Column::DeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DeviceConfig,
    #[sea_orm(has_many = "super::discount_to_group::Entity")]
    DiscountToGroup,
    #[sea_orm(has_many = "super::discount_to_product::Entity")]
    DiscountToProduct,
    #[sea_orm(has_many = "super::limits::Entity")]
    Limits,
}

impl Related<super::contract_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContractProducts.def()
    }
}

impl Related<super::device_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceConfig.def()
    }
}

impl Related<super::discount_to_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountToGroup.def()
    }
}

impl Related<super::discount_to_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountToProduct.def()
    }
}

impl Related<super::limits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Limits.def()
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::discount_to_group::Relation::Groups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::discount_to_group::Relation::Discounts.def().rev())
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        super::discount_to_product::Relation::Products.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::discount_to_product::Relation::Discounts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
