//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "dispenser_ports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub protocol: String,
    pub port_name: String,
    pub port_speed: i32,
    pub device_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_config::Entity",
        from = "Column::DeviceId",
        to = "super::device_config::Column::DeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DeviceConfig,
    #[sea_orm(has_many = "super::dispensers::Entity")]
    Dispensers,
}

impl Related<super::device_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceConfig.def()
    }
}

impl Related<super::dispensers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dispensers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
