//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "dispensers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub base_address: i32,
    pub port_id: String,
    pub camera_id: Option<String>,
    pub state: String,
    pub device_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cameras::Entity",
        from = "Column::CameraId",
        to = "super::cameras::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cameras,
    #[sea_orm(
        belongs_to = "super::device_config::Entity",
        from = "Column::DeviceId",
        to = "super::device_config::Column::DeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DeviceConfig,
    #[sea_orm(
        belongs_to = "super::dispenser_ports::Entity",
        from = "Column::PortId",
        to = "super::dispenser_ports::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DispenserPorts,
    #[sea_orm(has_many = "super::nozzles::Entity")]
    Nozzles,
}

impl Related<super::cameras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cameras.def()
    }
}

impl Related<super::device_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceConfig.def()
    }
}

impl Related<super::dispenser_ports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DispenserPorts.def()
    }
}

impl Related<super::nozzles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nozzles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
