//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fueling_order")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: String,
    pub d_created: DateTimeUtc,
    pub d_move: Option<DateTimeUtc>,
    #[sea_orm(unique)]
    pub order_item_id: String,
    pub nozzle_id: String,
    pub preset_volume: Decimal,
    pub preset_amount: Decimal,
    pub volume: Decimal,
    pub amount: Decimal,
    pub preset_type: String,
    pub fueling_type: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::nozzles::Entity",
        from = "Column::NozzleId",
        to = "super::nozzles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Nozzles,
    #[sea_orm(
        belongs_to = "super::order_items::Entity",
        from = "Column::OrderItemId",
        to = "super::order_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OrderItems,
}

impl Related<super::nozzles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nozzles.def()
    }
}

impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
