//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub group_type: String,
    pub mark_id: Option<String>,
    pub name: String,
    pub parent_id: Option<String>,
    pub device_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_config::Entity",
        from = "Column::DeviceId",
        to = "super::device_config::Column::DeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DeviceConfig,
    #[sea_orm(has_many = "super::discount_to_group::Entity")]
    DiscountToGroup,
    #[sea_orm(
        belongs_to = "super::marks::Entity",
        from = "Column::MarkId",
        to = "super::marks::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Marks,
    #[sea_orm(has_many = "super::products::Entity")]
    Products,
}

impl Related<super::device_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceConfig.def()
    }
}

impl Related<super::discount_to_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountToGroup.def()
    }
}

impl Related<super::marks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Marks.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::discounts::Entity> for Entity {
    fn to() -> RelationDef {
        super::discount_to_group::Relation::Discounts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::discount_to_group::Relation::Groups.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
