//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod clients;
pub mod device_config;
pub mod discount_to_group;
pub mod discount_to_product;
pub mod discounts;
pub mod groups;
pub mod limits;
pub mod marks;
pub mod order_item_discounts;
pub mod order_item_taxes;
pub mod order_items;
pub mod orders;
pub mod payments;
pub mod photos;
pub mod prices;
pub mod products;
pub mod roles;
pub mod shifts;
pub mod tax_to_product;
pub mod taxes;
pub mod units;
pub mod user_to_role;
pub mod users;
