//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "nozzles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub dispenser_id: String,
    #[sea_orm(unique)]
    pub address: i32,
    pub tank_id: String,
    pub device_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_config::Entity",
        from = "Column::DeviceId",
        to = "super::device_config::Column::DeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DeviceConfig,
    #[sea_orm(
        belongs_to = "super::dispensers::Entity",
        from = "Column::DispenserId",
        to = "super::dispensers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Dispensers,
    #[sea_orm(has_many = "super::fueling_order::Entity")]
    FuelingOrder,
    #[sea_orm(
        belongs_to = "super::tanks::Entity",
        from = "Column::TankId",
        to = "super::tanks::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tanks,
}

impl Related<super::device_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceConfig.def()
    }
}

impl Related<super::dispensers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dispensers.def()
    }
}

impl Related<super::fueling_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FuelingOrder.def()
    }
}

impl Related<super::tanks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tanks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
