//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub order_type: String,
    pub d_created: DateTimeUtc,
    pub d_move: Option<DateTimeUtc>,
    pub summ: Decimal,
    pub tax: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub discard: Option<String>,
    pub client_id: Option<String>,
    pub contract_id: Option<String>,
    pub contract_car_id: Option<String>,
    pub device_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clients::Entity",
        from = "Column::ClientId",
        to = "super::clients::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Clients,
    #[sea_orm(
        belongs_to = "super::device_config::Entity",
        from = "Column::DeviceId",
        to = "super::device_config::Column::DeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DeviceConfig,
    #[sea_orm(has_many = "super::order_items::Entity")]
    OrderItems,
    #[sea_orm(has_many = "super::payments::Entity")]
    Payments,
    #[sea_orm(has_many = "super::photos::Entity")]
    Photos,
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::device_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceConfig.def()
    }
}

impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItems.def()
    }
}

impl Related<super::payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payments.def()
    }
}

impl Related<super::photos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Photos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
