//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "order_item_to_contract_product")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub order_item_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub contract_product_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contract_products::Entity",
        from = "Column::ContractProductId",
        to = "super::contract_products::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    ContractProducts,
    #[sea_orm(
        belongs_to = "super::order_items::Entity",
        from = "Column::OrderItemId",
        to = "super::order_items::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    OrderItems,
}

impl Related<super::contract_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContractProducts.def()
    }
}

impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
