//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "order_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub order_id: String,
    pub product_id: String,
    pub count: Decimal,
    pub price: Decimal,
    pub discount: Decimal,
    pub cost: Decimal,
    pub tax: Decimal,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order_item_discounts::Entity")]
    OrderItemDiscounts,
    #[sea_orm(has_many = "super::order_item_taxes::Entity")]
    OrderItemTaxes,
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Orders,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Products,
}

impl Related<super::order_item_discounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItemDiscounts.def()
    }
}

impl Related<super::order_item_taxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItemTaxes.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
