//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub short_name: String,
    pub product_type: String,
    pub unit_id: String,
    #[sea_orm(unique)]
    pub bar_code: String,
    #[sea_orm(unique)]
    pub article: String,
    pub balance: Decimal,
    pub group_id: String,
    pub device_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_paths: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contract_products::Entity")]
    ContractProducts,
    #[sea_orm(
        belongs_to = "super::device_config::Entity",
        from = "Column::DeviceId",
        to = "super::device_config::Column::DeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DeviceConfig,
    #[sea_orm(has_many = "super::discount_to_product::Entity")]
    DiscountToProduct,
    #[sea_orm(
        belongs_to = "super::groups::Entity",
        from = "Column::GroupId",
        to = "super::groups::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Groups,
    #[sea_orm(has_many = "super::limits::Entity")]
    Limits,
    #[sea_orm(has_many = "super::order_items::Entity")]
    OrderItems,
    #[sea_orm(has_many = "super::prices::Entity")]
    Prices,
    #[sea_orm(has_many = "super::tanks::Entity")]
    Tanks,
    #[sea_orm(has_many = "super::tax_to_product::Entity")]
    TaxToProduct,
    #[sea_orm(
        belongs_to = "super::units::Entity",
        from = "Column::UnitId",
        to = "super::units::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Units,
}

impl Related<super::contract_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContractProducts.def()
    }
}

impl Related<super::device_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceConfig.def()
    }
}

impl Related<super::discount_to_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscountToProduct.def()
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groups.def()
    }
}

impl Related<super::limits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Limits.def()
    }
}

impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItems.def()
    }
}

impl Related<super::prices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prices.def()
    }
}

impl Related<super::tanks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tanks.def()
    }
}

impl Related<super::tax_to_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxToProduct.def()
    }
}

impl Related<super::units::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Units.def()
    }
}

impl Related<super::discounts::Entity> for Entity {
    fn to() -> RelationDef {
        super::discount_to_product::Relation::Discounts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::discount_to_product::Relation::Products.def().rev())
    }
}

impl Related<super::taxes::Entity> for Entity {
    fn to() -> RelationDef {
        super::tax_to_product::Relation::Taxes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tax_to_product::Relation::Products.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
