//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tax_to_product")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tax_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub product_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::taxes::Entity",
        from = "Column::TaxId",
        to = "super::taxes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Taxes,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::taxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Taxes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
