//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "taxes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub short_name: String,
    pub rate: Decimal,
    pub is_inclusive: bool,
    pub d_begin: DateTimeUtc,
    pub order_type: String,
    pub device_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
    pub version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_config::Entity",
        from = "Column::DeviceId",
        to = "super::device_config::Column::DeviceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DeviceConfig,
    #[sea_orm(has_many = "super::tax_to_product::Entity")]
    TaxToProduct,
}

impl Related<super::device_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceConfig.def()
    }
}

impl Related<super::tax_to_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxToProduct.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        super::tax_to_product::Relation::Products.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tax_to_product::Relation::Taxes.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
