pub const BS_PCODE: u8 = 0xF5;

//===BS COMMANDS=======
pub const BS_WRITE_PRICE: u8 = 0xB2;
pub const BS_READ_PRICE: u8 = 0xB6;
pub const BS_WRITE_SOLENOID: u8 = 0xD2;
pub const BS_READ_SOLENOID: u8 = 0xD6;
pub const BS_WRITE_DENCITY: u8 = 0xA2;
pub const BS_READ_DENCITY: u8 = 0xA6;
pub const BS_PRESET_AMOUNT: u8 = 0xB5;
pub const BS_PRESET_VOLUME: u8 = 0xB9;
pub const BS_READ_DISPENSER_STATE_BIT: u8 = 0xD5;
pub const BS_READ_FUELING_DATA: u8 = 0xD9;
pub const BS_READ_TOTAL: u8 = 0xC5;
pub const BS_READ_SHIFT_TOTAL: u8 = 0xC7;
pub const BS_START_FUELING: u8 = 0xC3;
pub const BS_STOP_FUELING: u8 = 0xCA;
pub const BS_ASK_FOR_CONTROL: u8 = 0xE5;
pub const BS_RETURN_CONTROL: u8 = 0xE7;
pub const BS_CLEAR_SHIFT_TOTAL: u8 = 0xEA;
pub const BS_PAUSE_FUELING: u8 = 0xBA;
pub const BS_RESUME_FUELING: u8 = 0xB3;
pub const BS_SELECT_NOZZLE: u8 = 0xA1;
//=====Additional functionality========
pub const BS_READ_PRESET: u8 = 0xA7;
pub const BS_READ_CARD_ID: u8 = 0xA8;
pub const BS_READ_ERROR_CODE: u8 = 0xA9;
pub const BS_READ_ID: u8 = 0xD7;
pub const BS_RESET_KB_PRESET_FLAG: u8 = 0xAA;
pub const BS_RESET_ERROR_FLAG: u8 = 0xAB;
pub const BS_READ_FLOW: u8 = 0xAD;
pub const BS_READ_PRESSURE: u8 = 0xAC;

pub const SH_PCODE: u8 = 0x2D;
pub const _SH_GETLITR: u8 = 0x04;
pub const SH_GETSTATUS: u8 = 0x01;
pub const SH_GETPRICE: u8 = 0x02;
pub const SH_GETSMENALITR: u8 = 0x0D;
pub const _SH_GETSMENABEZNAL: u8 = 0xE;
pub const _SH_GETSMENASUMMA: u8 = 0x0F;
pub const SH_GETTOTALLITR: u8 = 0x15;
pub const _SH_GETCCR: u8 = 0x16; //ВУУ запрашивает у ТРК данные по последним отпущенным ТРК объёмам топлива по всем адресам                                     стороны ТРК ( по 5 адресов ).
pub const _SH_GETPLOTNOST: u8 = 0x17;
pub const _SH_GETDAVLENIE: u8 = 0x19;
pub const _SH_SETDENSITY: u8 = 0x18; //Komanda ustanovka PLOTNOSTI
pub const SH_SETZAKRITSMENU: u8 = 0x0A;
pub const SH_SETKBON: u8 = 0x13;
pub const SH_SETKBOFF: u8 = 0x12;
pub const SH_SETSTOP: u8 = 0x0c; //sTOP
pub const SH_SETPAUSEMETAN: u8 = 0x0b; //Pauza esli metan
pub const SH_SETSTARTPAUZA: u8 = 0x11; //Start pauza
pub const SH_SETPUSKSUMMA: u8 = 0x09; //Komanda nachala otpuska topliva SUMMA
pub const SH_SETPUSKLITR: u8 = 0x05; //Komanda nachala otpuska topliva LITR
pub const SH_SETPRICE: u8 = 0x03; //Komanda ustanovka ceni

pub const SH_RESP_CCR: u8 = 0x00; //COMMAND CARRY OUT RESPONSE
pub const SH_RESP_CBR: u8 = 0xFF; //COMMAND BAD RESPONSE
pub const SH_RESP_SSR: u8 = 0x81; //STOP STATUS RESPONSE
pub const SH_RESP_AKR: u8 = 0x82; //AKTIVE KEYBOARD RESPONSE
pub const SH_RESP_AKRR: u8 = 0x83; //AKTIVE KEYBOARD REQUEST RESPONSE
pub const SH_RESP_AMAG: u8 = 0x84; //AKTIVE MODE ACTIVE GUN
pub const SH_RESP_AMNAG: u8 = 0x85; //AKTIVE MODE NO ACTIVE GUN
pub const SH_RESP_RPR: u8 = 0x91; //READ PRICE RESPONSE
pub const SH_RESP_CAR: u8 = 0x92; //CURRENT AMOUNT RESPONSE
pub const SH_RESP_MAR: u8 = 0x93; //MADE AMOUNT RESPONSE
pub const SH_RESP_RVC: u8 = 0x94; //READ VOLUME OF CHANGE
pub const SH_RESP_RVCC: u8 = 0x95; //READ VOLUME OF NON CACHE
pub const SH_RESP_CMCR: u8 = 0x96; //CACHE MONEY OF CHANGE RESPONSE
pub const SH_RESP_PVCR: u8 = 0x97; //PASSAGE VOLUME OF CHANGE RESPONSE
pub const SH_RESP_TCR: u8 = 0xA0; //TOTAL COUNTER REQUEST
pub const SH_RESP_DRR: u8 = 0xA2; //DENCITY REQUEST RESPONSE
pub const SH_RESP_PRR: u8 = 0xA3; //PRESSURE REQUEST RESPONSE
