// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentDTO } from "./PaymentDTO";

export type CloseOrderDTO = { order_id: string, payments: Array<PaymentDTO>, };
