// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentType } from "../PaymentType";

export type CreatePaymentDTO = { order_id: string, payment_type: PaymentType, summ: number, delivery: number, transaction: string, ticket: string, data: string, card_id: string | null, };
