// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for deleting product image
 */
export type DeleteProductImageDTO = { 
/**
 * Product ID
 */
product_id: string, 
/**
 * Image path to delete
 */
image_path: string, };
