// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresetType } from "../PresetType";

export type DispenserStartDTO = { address: number, preset_type: PresetType, preset: number, price: number, };
