// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for getting product image
 */
export type GetProductImageDTO = { 
/**
 * Relative path to the image
 */
image_path: string, };
