// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortOrder } from "../SortOrder";

export type LazyTableStateDTO<T, C> = { first: number, rows: number, page: number, sort_field: C, sort_order: SortOrder, filters: T, };
