// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitType } from "../LimitType";

export type LimitDTO = { id: string | null, device_id: string, card_id: string, limit_type: LimitType, product_id: string | null, d_begin: string, d_end: string, include_holidays: boolean, limit_value: number, discount_id: string | null, comment: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
