// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetaPaginatorDTO<T, M> = { page: number, count: number, limit: number, pageCount: number, items: Array<T>, meta: M, };
