// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderTypeTotals } from "./OrderTypeTotals";

export type OrderMovementSummaryMeta = { totalSum: number, totalTax: number, totalDiscount: number, 
/**
 * Money coming IN: Sales + Fuel Sales + Returns to Provider (sum + tax)
 */
totalIncoming: number, 
/**
 * Money going OUT: Purchases + Customer Returns (sum + tax)
 */
totalOutgoing: number, totalsByType: OrderTypeTotals, };
