// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter for product movement report
 */
export type ProductMovementFilter = { 
/**
 * Start of the period (ISO 8601 string)
 */
dateFrom: string, 
/**
 * End of the period (ISO 8601 string)
 */
dateTo: string, 
/**
 * Optional: filter by specific product ID
 */
productId: string | null, };
