// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductType } from "../ProductType";

export type ProductFilter = {
  search: string | null;
  productType: ProductType | null;
  groupId: string | null;
  activeDateFrom: string | null;
  activeDateTo: string | null;
};
