// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for uploaded image
 */
export type ProductImageResponse = { 
/**
 * Relative path to the saved image (for storing in DB)
 */
image_path: string, 
/**
 * Full URL/path for frontend to display
 */
image_url: string, };
