// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductType } from "../ProductType";

/**
 * Input DTO from frontend - no device_id or metadata required
 * This is the ONLY DTO needed for product operations
 */
export type ProductInputDTO = { id: string | null, name: string, short_name: string, product_type: ProductType, unit_id: string | null, bar_code: string, article: string, group_id: string | null, discount_ids: Array<string>, tax_ids: Array<string>, image_paths: Array<string>, };
