// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Movement data per product for the specified period
 */
export type ProductMovementItem = { productId: string, productName: string, productShortName: string | null, unitName: string | null, 
/**
 * Balance before the period started
 */
startBalance: number, 
/**
 * Quantity purchased (Income orders) during the period
 */
incomeQty: number, 
/**
 * Quantity sold (Sale + SaleDispenser orders) during the period
 */
saleQty: number, 
/**
 * Quantity returned by customers (Returns orders) during the period
 */
returnsQty: number, 
/**
 * Quantity returned to provider (Outcome orders) during the period
 */
outcomeQty: number, 
/**
 * Calculated end balance = start_balance + income_qty + returns_qty - sale_qty - outcome_qty
 */
endBalance: number, 
/**
 * Difference (end_balance - start_balance)
 */
diff: number, };
