// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductMovementItem } from "./ProductMovementItem";

/**
 * Full product movement report response
 */
export type ProductMovementReport = { items: Array<ProductMovementItem>, dateFrom: string, dateTo: string, };
