// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleType } from "../RoleType";

export type UpdateUserDTO = { id: string, full_name: string, phone_number: string, roles: Array<RoleType>, };
