// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for uploading product image (base64 encoded)
 */
export type UploadProductImageDTO = { 
/**
 * Product ID to associate the image with
 */
product_id: string, 
/**
 * Base64 encoded image data
 */
image_data: string, 
/**
 * File extension (e.g., "jpg", "png", "webp")
 */
extension: string, };
