import { type ProductEntity, getActivePrices } from "@/entities/product";
import Barcode from "@/shared/ui/barcode/Barcode";

interface ProductLabelProps {
  product: ProductEntity;
  size?: "small" | "medium" | "large";
}

export function ProductLabel({ product, size = "medium" }: ProductLabelProps) {
  const prices = getActivePrices(product);

  // Label dimensions based on size (in mm, converted to pixels at 96 DPI)
  const dimensions = {
    small: { width: "113px", height: "76px" }, // 30x20mm
    medium: { width: "189px", height: "113px" }, // 50x30mm
    large: { width: "378px", height: "189px" }, // 100x50mm
  };

  const fontSize = {
    small: { name: "10px", detail: "8px", barcode: "14px" },
    medium: { name: "14px", detail: "11px", barcode: "18px" },
    large: { name: "20px", detail: "14px", barcode: "24px" },
  };

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat("ru-RU", {
      style: "currency",
      currency: "UZS",
      minimumFractionDigits: 0,
    }).format(price);
  };

  const currentDate = new Date().toLocaleDateString("ru-RU");

  return (
    <div
      className="product-label bg-white text-black p-2 flex flex-col items-center justify-between border-2 border-dashed border-gray-300"
      style={{
        width: dimensions[size].width,
        height: dimensions[size].height,
        pageBreakAfter: "always",
        fontFamily: "monospace",
      }}
    >
      {/* Product Name */}
      <div
        className="text-center font-bold truncate w-full"
        style={{ fontSize: fontSize[size].name }}
      >
        {product.short_name || product.name}
      </div>

      {/* Barcode - displayed as text, actual barcode will be generated by printer */}
      {product.bar_code && (
        <div
          className="flex flex-col items-center my-1 font-mono"
          style={{ fontSize: fontSize[size].barcode }}
        >
          <div>Muham</div>
          <div className="tracking-wider"><Barcode /></div>
          <div className="mt-1">{product.bar_code}</div>
        </div>
      )}

      {/* Product Details */}
      <div
        className="text-center w-full space-y-0.5"
        style={{ fontSize: fontSize[size].detail }}
      >
        {/* Price */}
        <div className="font-bold">{formatPrice(prices.sale)}</div>

        {/* SKU */}
        {product.article && (
          <div className="text-gray-600">SKU: {product.article}</div>
        )}

        {/* Unit */}
        {product.unit && (
          <div className="text-gray-600">{product.unit.short_name}</div>
        )}

        {/* Date */}
        <div className="text-gray-500 text-xs">{currentDate}</div>
      </div>
    </div>
  );
}

/**
 * Generate plain text label for thermal printer
 * This creates a simple text-based label that thermal printers can handle
 */
export function generateProductLabelHTML(
  product: ProductEntity,
  size: "small" | "medium" | "large" = "medium"
): string {
  const prices = getActivePrices(product);
  const currentDate = new Date().toLocaleDateString("ru-RU");

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat("ru-RU", {
      style: "currency",
      currency: "UZS",
      minimumFractionDigits: 0,
    }).format(price);
  };

  // Helper function to center text
  const centerText = (text: string, width: number = 32): string => {
    if (text.length >= width) return text.substring(0, width);
    const padding = Math.floor((width - text.length) / 2);
    return " ".repeat(padding) + text + " ".repeat(padding);
  };

  // Helper function to create separator line
  const separator = (char: string = "=", width: number = 32): string => {
    return char.repeat(width);
  };

  // Width based on label size
  const widths = {
    small: 24,
    medium: 32,
    large: 48,
  };
  const width = widths[size];

  // Product name (truncate if too long)
  const productName = (product.short_name || product.name).substring(0, width);

  // Build the label as plain text
  const lines: string[] = [];

  lines.push(separator("=", width));
  lines.push(centerText(productName, width));
  lines.push(separator("=", width));
  lines.push("");

  // Barcode section
  if (product.bar_code) {
    lines.push(centerText("||||| ||||| |||||", width));
    lines.push(centerText(product.bar_code, width));
    lines.push("");
  }

  // Price
  lines.push(centerText(formatPrice(prices.sale), width));
  lines.push("");

  // Additional details
  if (product.article) {
    lines.push(centerText(`SKU: ${product.article}`, width));
  }

  if (product.unit) {
    lines.push(centerText(`Unit: ${product.unit.short_name}`, width));
  }

  lines.push("");
  lines.push(centerText(currentDate, width));
  lines.push(separator("=", width));
  lines.push("");
  lines.push("");

  const textContent = lines.join("\n");

  // Wrap in minimal HTML for the printer backend
  // The backend converts HTML to text, so we use <pre> to preserve formatting
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: 'Courier New', monospace;
      font-size: 12pt;
      white-space: pre;
    }
  </style>
</head>
<body>${textContent}</body>
</html>`;
}
