// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActDispState = { pist: number, is_start: boolean, hvalve: boolean, lvalve: boolean, is_motor: boolean, is_pause: boolean, is_keyboard: boolean, is_fueling: boolean, };
