// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraType } from "./CameraType";

export type CameraEntity = { id: string | null, camera_type: CameraType, name: string, address: string, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
