// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraType } from "./CameraType";

/**
 * Input DTO from frontend - no metadata required
 */
export type CameraDTO = { id: string | null, camera_type: CameraType, name: string, address: string, };
