// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardState } from "./CardState";
import type { ClientEntity } from "./ClientEntity";
import type { LimitEntity } from "./LimitEntity";

export type CardEntity = { id: string | null, device_id: string, client: ClientEntity | null, limits: Array<LimitEntity> | null, name: string, d_begin: string, d_end: string, state: CardState, comment: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
