// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientColumn = "Id" | "DeviceId" | "ClientType" | "Name" | "NameShort" | "DocumentCode" | "Address" | "TaxCode" | "Bank" | "Contact" | "Login" | "Password";
