// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientType } from "./ClientType";

/**
 * Input DTO from frontend - no device_id or metadata required
 */
export type ClientDTO = { id: string | null, client_type: ClientType, name: string, name_short: string, document_code: string | null, address: string | null, tax_code: string | null, bank: string | null, contact: string | null, login: string, password: string, };
