// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientType } from "./ClientType";

export type ClientFilter = { id: string | null, device_id: string | null, name: string | null, name_short: string | null, client_type: ClientType | null, document_code: string | null, address: string | null, tax_code: string | null, };
