// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientType } from "./ClientType";

export type ClientEntity = { id: string | null, device_id: string, client_type: ClientType, name: string, name_short: string, document_code: string | null, address: string | null, tax_code: string | null, bank: string | null, contact: string | null, login: string, password: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
