// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BsResp } from "./BsResp";
import type { ShResp } from "./ShResp";

export type CommResponse = { "Sh": [number, ShResp] } | { "BS": [number, BsResp] };
