// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestCmd } from "./RequestCmd";

export type CommRequest = { "Cmd": [number, RequestCmd] } | "Stop";
