// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContractCarDTO = { id: string | null, device_id: string, contract_id: string, name: string, comment: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
