// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractProductOrderItem } from "./ContractProductOrderItem";
import type { DiscountEntity } from "./DiscountEntity";
import type { ProductEntity } from "./ProductEntity";

export type ContractProductEntity = { id: string | null, contract_id: string, product: ProductEntity | null, order_items: Array<ContractProductOrderItem>, article: number, count: number, discount: DiscountEntity | null, };
