// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientEntity } from "./ClientEntity";
import type { ContractCarEntity } from "./ContractCarEntity";
import type { ContractProductEntity } from "./ContractProductEntity";

export type ContractEntity = { id: string | null, device_id: string, client: ClientEntity | null, name: string, contract_name: string, d_begin: string, d_end: string, contract_products: Array<ContractProductEntity>, contract_cars: Array<ContractCarEntity>, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
