// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContractFilter = { id: string | null, device_id: string | null, client_id: string | null, name: string | null, contract_name: string | null, d_begin: [string, string]|null, d_end: [string, string]|null, };
