// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContractProductDTO = { id: string | null, device_id: string, contract_id: string, product_id: string | null, article: number, count: number, discount_id: string | null, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
