// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContractDTO = { id: string | null, device_id: string, client_id: string | null, name: string, contract_name: string, d_begin: string, d_end: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
