// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContractProductOrderItem = { id: string, order_id: string, count: number, price: number, discount: number, cost: number, tax: number, };
