// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscountBoundType } from "./DiscountBoundType";
import type { DiscountType } from "./DiscountType";
import type { DiscountUnitType } from "./DiscountUnitType";
import type { OrderType } from "./OrderType";
import type { ProductType } from "./ProductType";

export type DiscountEntity = { id: string | null, name: string, discount_type: DiscountType, discount_bound_type: DiscountBoundType, discount_unit_type: DiscountUnitType, product_type: ProductType | null, bound: number, value: number, order_type: OrderType, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
