// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DispenserState } from "./DispenserState";

export type DispenserDTO = { id: string | null, name: string, base_address: number, port_id: string, camera_id: string | null, state: DispenserState, };
