// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DispenserProtocolType } from "./DispenserProtocolType";

export type DispenserPortEntity = { id: string | null, protocol: DispenserProtocolType, port_name: string, port_speed: number, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
