// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraEntity } from "./CameraEntity";
import type { DispenserError } from "./DispenserError";
import type { DispenserFuelingState } from "./DispenserFuelingState";
import type { DispenserPortEntity } from "./DispenserPortEntity";
import type { DispenserState } from "./DispenserState";
import type { NozzleEntity } from "./NozzleEntity";

export type DispenserEntity = { id: string | null, name: string, base_address: number, port_id: string, port: DispenserPortEntity | null, camera_id: string | null, camera: CameraEntity | null, nozzles: Array<NozzleEntity>, selected_nozzle_id: string | null, fueling_state: DispenserFuelingState, state: DispenserState, error: DispenserError | null, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
