// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DispenserFuelingState = { nozzle_down: boolean, pause: boolean, start: boolean, card: boolean, kb_control: boolean, kb_preset: boolean, is_error: boolean, };
