// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DispenserProtocolType } from "./DispenserProtocolType";

/**
 * Input DTO from frontend - no metadata required
 */
export type DispenserPortDTO = { id: string | null, protocol: DispenserProtocolType, port_name: string, port_speed: number, };
