// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Error = { "Dispenser": string } | "CtxFail" | "RecordNotFound" | { "StoreFailToCreate": string } | { "DBDataNotFound": string } | "DBConnection" | "Unknown" | "ClosedShiftErrror" | "Authentication" | "NotAuthorized" | "NotLoggedIn" | "NotAdministrator" | "DataAccess" | "OpenedShiftErrror" | { "Database": string } | { "General": string } | { "LicenseRestriction": string } | { "Validation": string };
