// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FuelingType } from "./FuelingType";
import type { PresetType } from "./PresetType";

export type FuelingOrderEntity = { id: string | null, title: string, order_item_id: string, nozzle_id: string, d_created: string, d_move: string|null, volume: number, amount: number, preset_volume: number, preset_amount: number, preset_type: PresetType, fueling_type: FuelingType, };
