// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FuelingType } from "./FuelingType";
import type { PresetType } from "./PresetType";

export type FuelingOrderFilter = { id: string | null, order_item_id: string | null, nozzle_id: string | null, d_created: [string, string]|null, d_move: [string, string]|null, fueling_type: FuelingType | null, preset_type: PresetType | null, title: string | null, };
