// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupType } from "./GroupType";

export type GroupDTO = { id: string | null, group_type: GroupType, mark_id: string | null, name: string, parent_id: string | null, discount_ids: Array<string>, };
