// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscountEntity } from "./DiscountEntity";
import type { GroupType } from "./GroupType";
import type { MarkEntity } from "./MarkEntity";

export type GroupEntity = { id: string | null, group_type: GroupType, mark: MarkEntity | null, name: string, parent_id: string | null, device_id: string, discounts: Array<DiscountEntity>, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
