// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderEntity } from "./OrderEntity";
import type { ProductEntity } from "./ProductEntity";

export type HubEvent = { "ActiveOrder": OrderEntity } | { "ProductUpdated": ProductEntity };
