// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardEntity } from "./CardEntity";
import type { DiscountEntity } from "./DiscountEntity";
import type { LimitType } from "./LimitType";
import type { ProductEntity } from "./ProductEntity";

export type LimitEntity = { id: string | null, card: CardEntity | null, limit_type: LimitType, product: ProductEntity | null, d_begin: string, d_end: string, include_holidays: boolean, limit_value: number, discount: DiscountEntity | null, comment: string, };
