// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarkEntity = { id: string | null, name: string, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
