// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NozzleSummaryData = { nozzle_id: string, fo_volume: number, fo_amount: number, oi_volume: number, oi_amount: number, };
