// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NozzleDTO = { id: string | null, address: number, dispenser_id: string, tank_id: string, fueling_order_id: string | null, };
