// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TankEntity } from "./TankEntity";

export type NozzleEntity = { id: string | null, address: number, dispenser_id: string, tank_id: string, tank: TankEntity | null, fueling_order_id: string | null, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
