// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractProductEntity } from "./ContractProductEntity";
import type { FuelingOrderEntity } from "./FuelingOrderEntity";
import type { OrderItemDiscountEntity } from "./OrderItemDiscountEntity";
import type { OrderItemTaxEntity } from "./OrderItemTaxEntity";
import type { ProductEntity } from "./ProductEntity";

export type OrderItemEntity = { id: string | null, order_id: string, product: ProductEntity | null, contract_product: ContractProductEntity | null, fueling_order: FuelingOrderEntity | null, count: number, price: number, discount: number, cost: number, tax: number, taxes: Array<OrderItemTaxEntity>, discounts: Array<OrderItemDiscountEntity>, };
