// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderType } from "./OrderType";

export type OrderFilter = { id: string | null, client_id: string | null, company: string | null, order_type: OrderType | null, d_move: [string, string]|null, };
