// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderItemTaxEntity = { id: string | null, order_item_id: string, name: string, value: number, rate: number, };
