// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderItemColumn = "Id" | "OrderId" | "ProductId" | "Count" | "Price" | "Discount" | "Cost" | "Tax";
