// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientEntity } from "./ClientEntity";
import type { ContractCarEntity } from "./ContractCarEntity";
import type { ContractEntity } from "./ContractEntity";
import type { OrderItemEntity } from "./OrderItemEntity";
import type { OrderType } from "./OrderType";
import type { PaymentEntity } from "./PaymentEntity";
import type { PictureEntity } from "./PictureEntity";

export type OrderEntity = { id: string | null, order_type: OrderType, d_created: string, d_move: string, summ: number, tax: number, discard: string | null, client: ClientEntity | null, contract: ContractEntity | null, contract_car: ContractCarEntity | null, items: Array<OrderItemEntity>, fueling_order_item_id: string | null, payments: Array<PaymentEntity>, pictures: Array<PictureEntity>, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
