// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderColumn = "Id" | "OrderType" | "DCreated" | "DMove" | "Summ" | "Tax" | "Discard" | "ClientId" | "ContractId" | "ContractCarId";
