// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderItemFilter = { id: string | null, order_id: string | null, product_id: string | null, min_count: number|null, max_count: number|null, min_price: number|null, max_price: number|null, min_cost: number|null, max_cost: number|null, min_tax: number|null, max_tax: number|null, min_discount: number|null, max_discount: number|null, product_name: string | null, has_fueling_order: boolean | null, };
