// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientEntity } from "./ClientEntity";
import type { OrderItemEntity } from "./OrderItemEntity";
import type { OrderType } from "./OrderType";
import type { PaymentEntity } from "./PaymentEntity";
import type { PictureEntity } from "./PictureEntity";

export type OrderEntity = { id: string | null, order_type: OrderType, d_created: string, d_move: string | null, summ: number, tax: number, discard: string | null, client: ClientEntity | null, items: Array<OrderItemEntity>, payments: Array<PaymentEntity>, pictures: Array<PictureEntity>, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
