// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentType } from "./PaymentType";

export type PaymentEntity = { id: string | null, payment_type: PaymentType, summ: number, delivery: number, transaction: string, ticket: string, discard: string | null, data: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
