// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaymentType = "Unknown" | "Cash" | "CashlessCard" | "CashlessContract" | "CashlessTicket" | "CashlessIdCard" | "CashlessBonus" | "CashlessFuel" | "CashlessYandex";
