// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhotoEntity = { id: string | null, d_created: string, camera_id: string, order_id: string, };
