// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PictureEntity = { id: string | null, d_created: string, order_id: string | null, camera_id: string | null, };
