// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceType } from "./PriceType";

export type PriceEntity = { id: string | null, product_id: string, start_time: string, value: number, price_type: PriceType, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
