// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceType } from "./PriceType";

export type PriceDTO = { id: string | null, product_id: string, start_time: string, value: number, price_type: PriceType, };
