// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscountEntity } from "./DiscountEntity";
import type { GroupEntity } from "./GroupEntity";
import type { PriceEntity } from "./PriceEntity";
import type { ProductType } from "./ProductType";
import type { TaxEntity } from "./TaxEntity";
import type { UnitEntity } from "./UnitEntity";

export type ProductEntity = { id: string | null, name: string, short_name: string, product_type: ProductType, unit: UnitEntity | null, bar_code: string, article: string, balance: number, group: GroupEntity | null, device_id: string, prices: Array<PriceEntity>, discounts: Array<DiscountEntity>, taxes: Array<TaxEntity>, sale_price: number | null, income_price: number | null, outcome_price: number | null, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, image_paths: Array<string>, };
