// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShiftDispenserData = { dispenser_name: string, nozzle_addres: string, shift_volume: number, shift_amount: number, total_volume: number, total_amount: number, calc_volume: number, calc_amount: number, };
