// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShiftData = { number: number, gas: string, temperature: number, density: number, level_current: number, volume_current: number, level_water: number, volume_water: number, level_measure: number, level_water_measure: number, volume_gas_calc: number, volume_gas_measure: number, volume_gas_corr: number};
