// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShiftData } from "./ShiftData";
import type { UserEntity } from "./UserEntity";

export type ShiftEntity = { id: string | null, d_open: string, d_close: string | null, user_open: UserEntity, user_close: UserEntity | null, data_open: Array<ShiftData>, data_close: Array<ShiftData> | null, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
