// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShiftFilter = { id: string | null, user_open_id: string | null, user_close_id: string | null, d_open: [string, string]|null, d_close: [string, string]|null, };
