// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActDispState } from "./ActDispState";
import type { FuelingType } from "./FuelingType";

export type ShResp = { "CommandOk": never[] } | { "CommandBad": never[] } | { "StopStatus": ActDispState } | { "ActiveKeyboard": [FuelingType, ActDispState, number] } | { "ActiveKeyboardRequest": [FuelingType, ActDispState, number] } | { "ActiveModeActiveGun": [ActDispState, FuelingType, number, number] } | { "ActiveModeNoActiveGun": [ActDispState, FuelingType, number, number] } | { "ReadPrice": number } | { "CurrentAmount": [ActDispState, FuelingType, number, number] } | { "MadeAmountResponse": [ActDispState, number, number, number] } | { "ReadVolumeOfChange": number } | { "ReadVolumeOfNonCache": number } | { "CacheMoneyOfChange": number } | { "PassageVolumeOfChange": number } | { "TotalCounter": number } | { "Dencity": number } | { "Pressure": number };
