// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductEntity } from "./ProductEntity";
import type { TankProtocolType } from "./TankProtocolType";

export type TankEntity = { id: string | null, name: string, protocol: TankProtocolType | null, address: number | null, server_address: string | null, server_port: number | null, port_name: string | null, port_speed: number | null, product_id: string, product: ProductEntity | null, balance: number, volume_max: number, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
