// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TankProtocolType } from "./TankProtocolType";

export type TankDTO = { id: string | null, name: string, protocol: TankProtocolType | null, address: number | null, server_address: string | null, server_port: number | null, port_name: string | null, port_speed: number | null, product_id: string, balance: number, volume_max: number, };
