// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderType } from "./OrderType";

export type TaxDTO = { id: string | null, name: string, short_name: string, rate: number, is_inclusive: boolean, d_begin: string, order_type: OrderType, };
