// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderType } from "./OrderType";

export type TaxEntity = { id: string | null, name: string, short_name: string, rate: number, is_inclusive: boolean, d_begin: string, order_type: OrderType, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
