// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleType } from "./RoleType";

export type UserEntity = { id: string | null, full_name: string, username: string, phone_number: string, roles: Array<RoleType>, device_id: string, created_at: string, updated_at: string, deleted_at: string | null, version: bigint, };
