pub mod camera_usecases;
pub mod card_usecases;
pub mod client_usecases;
pub mod contrac_car_usecases;
pub mod contract_product_usecases;
pub mod contract_usecases;
pub mod device_config_usecase;
pub mod discount_usecases;
pub mod dispenser_control_usecases;
pub mod dispenser_port_usecases;
pub mod dispenser_response_usecases;
pub mod dispenser_usecases;
pub mod group_usecases;
pub mod limit_usecases;
pub mod mark_usecases;
pub mod nozzle_usecases;
pub mod order_item_usecases;
pub mod order_usecases;
pub mod payment_usecases;
pub mod photo_usecases;
pub mod price_usecases;
pub mod product_usecases;
pub mod shift_usecases;
// pub mod shop_usecases; // DELETED - using device_config instead
// pub mod station_usecases; // DELETED - using device_config instead
pub mod tank_usecases;
pub mod tax_usecases;
pub mod unit_usecases;
pub mod user_usecases;
